
# SEO settings
title: "Bromat"
title2: ""
description: "Computer Graphics, Physics based animation, etc."
keywords: "Programming, Computer Graphics, Fluid Simulation"
url: mathiasb17.github.io # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/mathiasb17/mathiasb17.github.io
disqus_shortname: "Mathiasb17"
#twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Mathias Brousset"
  job      : "Ph.D. Student in Computer Graphics"
  bio      : ""
  thumb    : /images/author.jpg
  email    : mathiasb17@gmail.com
  url      : http://mathiasb17.github.io
  github   : http://github.com/mathiasb17
#  twitter  : http://twitter.com/HeiswayiNrird
#  facebook : https://www.facebook.com/profile.php?id=1257583160
#  linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
