
# SEO settings
title: "Mathias Brousset"
title2: ""
description: "Mathias Brousset homepage"
keywords: "mathias, brousset, homepage, website, computer, science"
url: http://bromat.fr # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

#google_analytics: UA-XXXXX-XX
repo: http://github.com/mathiasb17/mathiasb17.github.io
#disqus_shortname: "Mathiasb17"
#twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Mathias Brousset"
  job      : "Software and Firmware Engineer"
  bio      : ""
  thumb    : /images/author.jpg
  email    : mathiasb17@gmail.com
  url      : http://bromat.fr
  github   : http://github.com/mathiasb17
  facebook : https://www.facebook.com/mathias.brousset
  linkedin : https://www.linkedin.com/in/mathias-brousset-12949b45

# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: "@HeiswayiNrird"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
  - slug : research
    title: Research

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "vendor/bundle"]

# recurrent stuff
icon_pdf: <i class="fa fa-file-pdf-o" style="font-size:16px;color:red"></i>
icon_site: <i class="fa fa-file-code-o" style="font-size:16px"></i>

